stages:
  prepare:
    cmd: python3 pipeline/prepare.py
    deps:
    - data.zip
    - pipeline/prepare.py
    outs:
    - data/:
        cache: false
  train:
    cmd: python3 pipeline/train.py
    deps:
    - data/
    - pipeline/train.py
    outs:
    - model.h5:
        cache: false
    metrics:
    - metrics.csv:
        cache: false

