stages:
  split:
    cmd: python3 src/pipeline/split.py 
      --gcs-path ${dataset.gcs_path}
      --train-split-path ${split.train_split_path}
      --val-split-path ${split.val_split_path} 
      --images-count-path ${split.images_count_path}
      --validation-split ${split.validation_split}
      --image-size ${dataset.image_size}
    deps:
    - src/pipeline/split.py
    - remote://${dataset.gcs_path_remote_alias}
    outs:
    - ${split.train_split_path}
    - ${split.val_split_path}
    - ${split.images_count_path}

