stages:
  split:
    cmd: python3 src/pipeline/split.py --gcs-path ${dataset.gcs_path} --train-split-path
      ${split.train_split_path} --val-split-path ${split.val_split_path} --images-count-path
      ${split.images_count_path} --validation-split ${split.validation_split} --image-size
      ${dataset.image_size}
    deps:
    - src/pipeline/split.py
    - remote://${dataset.gcs_path_remote_alias}
    outs:
    - ${split.train_split_path}
    - ${split.val_split_path}
    - ${split.images_count_path}

  train:
    cmd: python src/pipeline/train.py 
      --lr-start ${train.lr.start} 
      --classes-path ${dataset.classes_path} 
      --image-size ${dataset.image_size}
      --epochs ${train.epochs}
      --batch-size ${train.batch_size}
      --train-split-path ${split.train_split_path}
      --val-split-path ${split.val_split_path}
      --images-count-path ${split.images_count_path}
      --saved-model-path ${train.saved_model_path}
      --train-plot-path ${train.train_plot_path}
      --checkpoint-dir ${checkpoint.dir_path}
      --checkpoint-prefix ${checkpoint.prefix}
    deps:
    - src/pipeline/train.py
    - ${split.train_split_path}
    - ${split.val_split_path}
    - ${split.images_count_path}
    - ${dataset.classes_path}
    outs:
    - ${train.saved_model_path}
    - ${checkpoint.dir_path}/${checkpoint.prefix}.index
    - ${checkpoint.dir_path}/${checkpoint.prefix}.data-00000-of-00001
    - ${checkpoint.dir_path}/checkpoint
    plots:
    - ${train.train_plot_path}:
        x: epoch
        y: accuracy
  evaluate:
      cmd: python src/pipeline/evaluate.py 
        --image-size ${dataset.image_size}
        --batch-size ${train.batch_size}
        --val-split-path ${split.val_split_path}
        --saved-model-path ${train.saved_model_path}
        --evaluate-metrics-path ${evaluate.evaluate_metrics_path}
      deps:
      - src/pipeline/evaluate.py
      - ${split.val_split_path}
      - ${train.saved_model_path}
      metrics:
      - ${evaluate.evaluate_metrics_path}:
          cache: false

