stages:
  split:
    cmd: python3 src/split.py
        --gcs-path ${dataset.gcs_patn} 
        --train-split-path ${split.train_split_path}
        --val-split-path ${split.val_split_path}
        --validation-split ${split.validation_split}
        --image-size ${dataset.image_size}
    deps:
    - src/split.py
    outs:
    - ${split.train_split_path}
    - ${split.val_split_path}
