dataset:
  image_size: 331
  gcs_patn: gs://kaggle-data-tpu

split:
  train_split_path: data/interim/train_split.json
  val_split_path: data/interim/val_split.json
  validation_split: 0.19

train:
  nb_validation_samples: 800
  epochs: 10
  batch_size: 10

